name: Reusable workflow

on:
  workflow_dispatch:
    inputs:
      STATEBUCKET:
        required: true
        option:
         - mybucksoham-cicd
      ENVIRONMENT:
        required: true
        option:
         - test
      REGION:
        required: true
        option:
         - ap-south-1
jobs:
  build-test-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Terraformplan
        uses: MrGandhe/github-shared/Terraformplan/action.yml@main
        with:
         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         STATEBUCKET : ${{ inputs.STATEBUCKET }}
         REGION : ${{ inputs.REGION }}
         ENVIRONMENT : ${{ inputs.ENVIRONMENT }}
