name: Reusable workflow

on:
  workflow_call:
    inputs:
 STATEBUCKET:
    description: 'statebucket name'
    required: true  
  ENVIRONMENT:
     description: 'environment name'
     required: true
  REGION:
     description: 'region'
     required: true
jobs:
  build-test-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Terraformplan
        uses: MrGandhe/github-shared/Terraformplan@main
        with:
          docker_image: ${{ inputs.bucketname }}
